module RegistrationsHelper
  def return_country_select
   ['United States',
     'Canada',
     'Australia',
     'Austria',
     'Belgium',
     'Bolivia',
     'Bosnia and Herzegovina',
     'Brazil',
     'Bulgaria',
     'Croatia',
     'Cyprus',
     'Czech Republic',
     'Denmark',
     'Ecuador',
     'Estonia',
     'Faroe Islands',
     'Finland',
     'France',
     'Georgia',
     'Germany',
     'Gibraltar',
     'Greece',
     'Greenland',
     'Hungary',
     'Iceland',
     'Ireland',
     'Israel',
     'Italy',
     'Latvia',
     'Lebanon',
     'Liechtenstein',
     'Lithuania',
     'Luxembourg',
     'Malta',
     'Moldova',
     'Monaco',
     'Montenegro',
     'Netherlands',
     'New Caledonia',
     'New Zealand',
     'Norway',
     'Poland',
     'Portugal',
     'Romania',
     'Russian Federation',
     'Serbia',
     'Slovakia',
     'Slovenia',
     'Spain',
     'Sweden',
     'Switzerland',
     'Turkey',
     'Turkmenistan',
     'Ukraine',
     'United Kingdom',
     'United States',
     'Uruguay',
     'Vanuatu',
     'Vatican City',
     'Venezuela',
     'Virgin Islands, British',
     'Virgin Islands, U.S.',
     'Wallis and Futuna',
     'Other']
  end
end
